openapi: 3.0.0
info:
  description: Needs no description.
  title: UniManager API Documentation
  version: 0.0.1
servers:
- url: /
paths:
  /api/account:
    get:
      operationId: account.index
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
      summary: Show account information.
      tags:
      - Users
      x-accepts: application/json
  /api/account/update:
    patch:
      operationId: account.update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestBody'
        description: The updated data to save.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: User Response
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
          description: Unprocessable Content
      summary: Update account information.
      tags:
      - Users
      x-contentType: application/json
      x-accepts: application/json
  /api/departments:
    get:
      operationId: departments.index
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentArray'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
      summary: List all departments.
      tags:
      - Departments
      x-accepts: application/json
  /api/departments/store:
    post:
      operationId: departments.store
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              type: object
        description: The new department's name.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
          description: Unprocessable Content
      summary: Creates a new Department.
      tags:
      - Departments
      x-contentType: application/json
      x-accepts: application/json
  /api/departments/{departmentId}/find:
    get:
      operationId: departments.find
      parameters:
      - description: Numeric ID of the Department
        explode: false
        in: path
        name: departmentId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: Not Found
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
      summary: Get a Department by ID
      tags:
      - Departments
      x-accepts: application/json
  /api/departments/{departmentId}/update:
    patch:
      operationId: departments.update
      parameters:
      - description: Numeric ID of the Department
        explode: false
        in: path
        name: departmentId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: Not Found
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
          description: Unprocessable Content
      summary: Update the identified Department.
      tags:
      - Departments
      x-accepts: application/json
  /api/departments/{departmentId}/delete:
    delete:
      operationId: departments.delete
      parameters:
      - description: Numeric ID of the Department
        explode: false
        in: path
        name: departmentId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: Not Found
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
          description: Unprocessable Content
      summary: Delete the identified Department.
      tags:
      - Departments
      x-accepts: application/json
  /api/offers/job/paginated:
    get:
      operationId: offers.job.paginated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
          description: Forbidden
        "419":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_419'
          description: CSRF Mismatch
      summary: List all job offers in a paginated manner.
      tags:
      - Job Offers
      x-accepts: application/json
components:
  parameters:
    DepartmentId:
      description: Numeric ID of the Department
      explode: false
      in: path
      name: departmentId
      required: true
      schema:
        format: int64
        type: integer
      style: simple
    MajorId:
      description: Numeric ID of the Major
      explode: false
      in: path
      name: majorId
      required: true
      schema:
        format: int64
        type: integer
      style: simple
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  responses:
    OK:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_200_1'
      description: OK
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_404'
      description: Not Found
    UnprocessableContent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_422'
      description: Unprocessable Content
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_403'
      description: Forbidden
    CSRF:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_419'
      description: CSRF Mismatch
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_200'
      description: User Response
    DepartmentList:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DepartmentArray'
      description: OK
    JobOfferPaginated:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_200_2'
      description: OK
    ScholarshipOfferPaginated:
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: '#/components/schemas/ScholarshipOfferArray'
              links:
                items:
                  $ref: '#/components/schemas/PaginatedLink'
                type: array
              current_page:
                example: 5
                type: integer
              per_page:
                default: 15
                example: 15
                type: integer
              from:
                example: 1
                nullable: true
                type: integer
              to:
                example: 15
                nullable: true
                type: integer
              total:
                example: 64
                type: integer
            type: object
      description: OK
  schemas:
    User:
      example:
        country: United States of America
        city: Charlotte
        id_card: id_card
        last_name: Turner
        email_verified_at: 2000-01-23T04:56:07.000+00:00
        middle_name: Latoya
        password: password
        phone: phone
        address_line_1: address_line_1
        id: 0
        address_line_2: address_line_2
        remember_token: remember_token
        region: North Carolina
        postal_code: "28001"
        first_name: Tina
        email: tinaturner@example.com
      properties:
        id:
          format: int64
          type: integer
        first_name:
          example: Tina
          type: string
        middle_name:
          example: Latoya
          nullable: true
          type: string
        last_name:
          example: Turner
          type: string
        email:
          example: tinaturner@example.com
          format: email
          type: string
        email_verified_at:
          format: date-time
          nullable: true
          type: string
        remember_token:
          nullable: true
          type: string
        password:
          format: password
          type: string
        phone:
          type: string
        address_line_1:
          type: string
        address_line_2:
          nullable: true
          type: string
        city:
          example: Charlotte
          type: string
        region:
          example: North Carolina
          type: string
        country:
          example: United States of America
          type: string
        postal_code:
          example: "28001"
          type: string
        id_card:
          type: string
      type: object
    UserRequestBody:
      example:
        country: United States of America
        phone: phone
        city: Charlotte
        address_line_1: address_line_1
        id_card: id_card
        last_name: Turner
        address_line_2: address_line_2
        middle_name: Latoya
        region: North Carolina
        postal_code: "28001"
        first_name: Tina
      properties:
        first_name:
          example: Tina
          type: string
        middle_name:
          example: Latoya
          nullable: true
          type: string
        last_name:
          example: Turner
          type: string
        phone:
          type: string
        address_line_1:
          type: string
        address_line_2:
          nullable: true
          type: string
        city:
          example: Charlotte
          type: string
        region:
          example: North Carolina
          type: string
        country:
          example: United States of America
          type: string
        postal_code:
          example: "28001"
          type: string
        id_card:
          type: string
      type: object
    Department:
      example:
        name: DCIC
        id: 0
      properties:
        id:
          format: int64
          type: integer
        name:
          example: DCIC
          type: string
      type: object
    DepartmentArray:
      items:
        $ref: '#/components/schemas/Department'
      type: array
    Major:
      properties:
        id:
          format: int64
          type: integer
        name:
          example: Computer Science
          type: string
        department_id:
          format: int64
          type: integer
      type: object
    MajorArray:
      items:
        $ref: '#/components/schemas/Major'
      type: array
    JobOffer:
      example:
        benefits: benefits
        interview_at: 2000-01-23T04:56:07.000+00:00
        requirements: requirements
        starts_at: 2000-01-23T04:56:07.000+00:00
        public: true
        department_id: 6
        description: description
        id: 0
        ends_at: 2000-01-23T04:56:07.000+00:00
        title: title
        department:
          name: DCIC
          id: 0
      properties:
        id:
          format: int64
          type: integer
        title:
          type: string
        description:
          type: string
        requirements:
          type: string
        benefits:
          type: string
        interview_at:
          format: date-time
          type: string
        department_id:
          format: int64
          type: integer
        starts_at:
          format: date-time
          type: string
        ends_at:
          format: date-time
          type: string
        public:
          type: boolean
        department:
          $ref: '#/components/schemas/Department'
      type: object
    JobOfferArray:
      items:
        $ref: '#/components/schemas/JobOffer'
      type: array
    ScholarshipOffer:
      properties:
        id:
          format: int64
          type: integer
        title:
          type: string
        description:
          type: string
        requirements:
          type: string
        starts_at:
          format: date-time
          type: string
        ends_at:
          format: date-time
          type: string
        public:
          type: boolean
        majors:
          items:
            $ref: '#/components/schemas/Major'
          type: array
          uniqueItems: true
      type: object
    ScholarshipOfferArray:
      items:
        $ref: '#/components/schemas/ScholarshipOffer'
      type: array
    Application:
      properties:
        id:
          format: int64
          type: integer
        number:
          format: int64
          type: integer
        user_id:
          format: int64
          type: integer
        user:
          $ref: '#/components/schemas/User'
        offer_id:
          format: int64
          type: integer
        offer_type:
          type: string
        status:
          type: string
        offer:
          oneOf:
          - $ref: '#/components/schemas/JobOffer'
          - $ref: '#/components/schemas/ScholarshipOffer'
          type: object
        major_id:
          format: int64
          nullable: true
          type: integer
        major:
          $ref: '#/components/schemas/Major'
        document_files:
          items:
            $ref: '#/components/schemas/DocumentationFile'
          type: array
          uniqueItems: true
        comments:
          items:
            $ref: '#/components/schemas/Comment'
          type: array
          uniqueItems: true
      type: object
    ApplicationArray:
      items:
        $ref: '#/components/schemas/Application'
      type: array
    DocumentationFile:
      properties:
        id:
          format: int64
          type: integer
        path:
          format: uri
          type: string
        application_id:
          format: int64
          type: integer
      type: object
    Comment:
      properties:
        id:
          format: int64
          type: integer
        text:
          format: uri
          type: string
        application_id:
          format: int64
          type: integer
        user_id:
          format: int64
          type: integer
        user:
          $ref: '#/components/schemas/User'
      type: object
    PaginatedLink:
      example:
        active: true
        label: "5"
        url: https://unimanager.snowlinks.net/api/model?page=5
      properties:
        url:
          example: https://unimanager.snowlinks.net/api/model?page=5
          nullable: true
          type: string
        label:
          example: "5"
          type: string
        active:
          type: boolean
      type: object
    inline_response_403:
      properties:
        message:
          example: You do not have access rights to perform this action.
          type: string
      type: object
    inline_response_419:
      properties:
        message:
          example: CSRF Mismatch
          type: string
      type: object
    inline_response_200:
      example:
        country: United States of America
        city: Charlotte
        id_card: id_card
        last_name: Turner
        middle_name: Latoya
        phone: phone
        address_line_1: address_line_1
        id: 0
        address_line_2: address_line_2
        region: North Carolina
        postal_code: "28001"
        first_name: Tina
        email: tinaturner@example.com
      properties:
        id:
          format: int64
          type: integer
        first_name:
          example: Tina
          type: string
        middle_name:
          example: Latoya
          nullable: true
          type: string
        last_name:
          example: Turner
          type: string
        email:
          example: tinaturner@example.com
          format: email
          type: string
        phone:
          type: string
        address_line_1:
          type: string
        address_line_2:
          nullable: true
          type: string
        city:
          example: Charlotte
          type: string
        region:
          example: North Carolina
          type: string
        country:
          example: United States of America
          type: string
        postal_code:
          example: "28001"
          type: string
        id_card:
          type: string
      type: object
    inline_response_422_response_data:
      properties:
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        message:
          example: The email field is required.
          type: string
      type: object
    inline_response_422_response:
      properties:
        status:
          example: 422
          maximum: 422
          minimum: 422
          type: integer
        data:
          $ref: '#/components/schemas/inline_response_422_response_data'
      type: object
    inline_response_422:
      properties:
        response:
          $ref: '#/components/schemas/inline_response_422_response'
      type: object
    inline_object:
      properties:
        name:
          type: string
      type: object
    inline_response_200_1:
      example:
        message: The action was performed successfully.
      properties:
        message:
          example: The action was performed successfully.
          type: string
      type: object
    inline_response_404:
      properties:
        message:
          example: The page was not found.
          type: string
      type: object
    inline_response_200_2:
      example:
        per_page: 15
        total: 64
        data:
        - benefits: benefits
          interview_at: 2000-01-23T04:56:07.000+00:00
          requirements: requirements
          starts_at: 2000-01-23T04:56:07.000+00:00
          public: true
          department_id: 6
          description: description
          id: 0
          ends_at: 2000-01-23T04:56:07.000+00:00
          title: title
          department:
            name: DCIC
            id: 0
        - benefits: benefits
          interview_at: 2000-01-23T04:56:07.000+00:00
          requirements: requirements
          starts_at: 2000-01-23T04:56:07.000+00:00
          public: true
          department_id: 6
          description: description
          id: 0
          ends_at: 2000-01-23T04:56:07.000+00:00
          title: title
          department:
            name: DCIC
            id: 0
        links:
        - active: true
          label: "5"
          url: https://unimanager.snowlinks.net/api/model?page=5
        - active: true
          label: "5"
          url: https://unimanager.snowlinks.net/api/model?page=5
        from: 1
        to: 15
        current_page: 5
      properties:
        data:
          items:
            $ref: '#/components/schemas/JobOffer'
          type: array
        links:
          items:
            $ref: '#/components/schemas/PaginatedLink'
          type: array
        current_page:
          example: 5
          type: integer
        per_page:
          default: 15
          example: 15
          type: integer
        from:
          example: 1
          nullable: true
          type: integer
        to:
          example: 15
          nullable: true
          type: integer
        total:
          example: 64
          type: integer
      type: object

